print("-"*44)
print("|                                          |")
print("| Name : Mustafa agasiya wala              |")
print("| Address : new saifee nagar               |")
print("| Age : 17                                 |")
print("| class : 11                               |")
print("| section : B                              |")
print("| Mobile no. : 8319908319                  |")
print("|                                          |")
print("-"*44)
